export const CREATE_ACCOMMODATION = "CREATE_ACCOMMODATION";
export const CREATE_ACCOMMODATION_FAILED = "CREATE_ACCOMMODATION_FAILED";
export const FETCH_ACCOMMODATIONS = "FETCH_ACCOMMODATIONS";
export const FETCH_ACCOMMODATIONS_FAILED = "FETCH_ACCOMMODATIONS_FAILED";
export const UPDATE_ACCOMMODATION = "UPDATE_ACCOMMODATION";
export const DELETE_ACCOMMODATION = "DELETE_ACCOMMODATION";
